#!/bin/bash

git rm --cached .vscode/
git rm --cached SoftwareGasControl/
git rm --cached __pycache__/
git rm --cached controller/__pycache__/
git rm --cached git_rm_cached.bat
git rm --cached gitignore
git rm --cached model/ElectricalMeasurementsTypes/__pycache__/
git rm --cached model/__pycache__/AutomaticMode.cpython-313.pyc
git rm --cached model/__pycache__/DataManager.cpython-313.pyc
git rm --cached model/__pycache__/ManualMode.cpython-313.pyc
git rm --cached model/__pycache__/MassFlowController.cpython-313.pyc
git rm --cached packets/DataMeasurement/__pycache__/DataMeasurement.cpython-313.pyc
git rm --cached packets/DataMeasurement/__pycache__/DataMeasurementFake.cpython-313.pyc
git rm --cached packets/DataMeasurement/__pycache__/MockTrx.cpython-313.pyc
git rm --cached packets/DataMeasurement/__pycache__/Trx.cpython-313.pyc
git rm --cached packets/DataMeasurement/__pycache__/__init__.cpython-313.pyc
git rm --cached packets/ExcelController/__pycache__/Configuration.cpython-313.pyc
git rm --cached packets/ExcelController/__pycache__/ExcelController.cpython-313.pyc
git rm --cached packets/ExcelController/__pycache__/Measurement.cpython-313.pyc
git rm --cached packets/ExcelController/__pycache__/OutputExcel.cpython-313.pyc
git rm --cached packets/ExcelController/__pycache__/__init__.cpython-313.pyc
git rm --cached packets/Keithley/__pycache__/EthernetConnection.cpython-313.pyc
git rm --cached packets/Keithley/__pycache__/Keithley.cpython-313.pyc
git rm --cached packets/Keithley/__pycache__/KeithleyFake.cpython-313.pyc
git rm --cached packets/Keithley/__pycache__/__init__.cpython-313.pyc
git rm --cached packets/MassFlowDevice/__pycache__/MassFlowDevice.cpython-313.pyc
git rm --cached packets/MassFlowDevice/__pycache__/MassFlowDeviceFake.cpython-313.pyc
git rm --cached packets/MassFlowDevice/__pycache__/__init__.cpython-313.pyc
git rm --cached view/__pycache__/App.cpython-313.pyc
git rm --cached view/__pycache__/ElectricalTypeDialog.cpython-313.pyc
git rm --cached view/__pycache__/MenuController.cpython-313.pyc
git rm --cached view/__pycache__/TerminalView.cpython-313.pyc
